# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-06 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20170405_1439'),
        ('courses', '0007_video_learn_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseresource',
            options={'verbose_name': '\u8bfe\u7a0b\u8d44\u6e90', 'verbose_name_plural': '\u8bfe\u7a0b\u8d44\u6e90'},
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='\u8bb2\u5e08'),
        ),
    ]
