# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-10 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170324_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='birthday',
            new_name='birday',
        ),
    ]
