# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-05 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_teacher_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='ourse_nums',
            new_name='course_nums',
        ),
    ]
